require("mini.move").setup()
require("mini.pairs").setup()
require("mini.notify").setup()
require("mini.starter").setup()
require('mini.cursorword').setup()
require("mini.indentscope").setup()
require("mini.animate").setup({ scroll = { enable = false } })
